version: '3'


networks:
  hexagonal-arch:
    driver: bridge

services:

  db:
    image: postgres:15
    restart: always
    hostname: psql15
    networks:
      - hexagonal-arch
    environment:
      POSTGRES_PASSWORD: postgres123

  alpha:
    image: mborrini/hexagonal-arch
    restart: 'no'
    hostname: alpha
    ports:
      - "8000:8080"
    networks:
      - hexagonal-arch
