
spring:
  application:
    name: Alpha
  datasource:
    url: jdbc:postgresql://psql15:5432/postgres
    username: postgres
    password: postgres123
  jpa:
    hibernate:
      ddl-auto: create-drop